### ISSUE TITLE
Add support for typescript in templates

### ISSUE THREAD

**Issue by jeansson** [nxtedition/create-caspar-graphics#1]
This is great stuff! It would be awesome to have support for TypeScript as well, maybe by passing "--lang" ts or something like that. This will generate a templates->example->index.ts instead and would use the ts compiler instead of babel i guess. If that is not an option maybe this could be: https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/

**Comment by tobiasandersen** [comment]
Thanks! 

Supporting TypeScript would be really nice. But we don't use it ourselves so I don't see us working on adding support for it anytime soon. I'd love a PR though! 

There's currently an [open PR](https://github.com/facebook/create-react-app/pull/4837) in the create-react-app repo about adding support for TS. The idea is basically to automatically detect TS by looking at the extension. Maybe this would be even easier now with [blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7](blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7)?

The way [Razzle](https://github.com/jaredpalmer/razzle) solves it is by allowing [customizations to the webpack config](https://github.com/jaredpalmer/razzle#extending-webpack). I've been thinking about doing the same, since it really opens up a lot of options. 

Regardless of the approach, I think having a "lang" option when running create would be a good idea!

What do you think?

**Comment by tobiasandersen** [comment]
This is now supported.
