### ISSUE TITLE
Access package.json from within templates

### ISSUE THREAD

**Issue by tobiasandersen** [nxtedition/create-caspar-graphics#36]
This was a request from @axelboberg, but I can't remember why you wanted it. Can you elaborate a bit on why it would be useful? :)

**Comment by axelboberg** [comment]
Sure thing!

As a step to make working with responsive templates and different aspect ratios easier it would be good to have access to at least the `caspar-graphics` object from package.json since that's where the resolution is set.

However, this should probably be discussed together with if and how v2 will handle different resolutions and aspect ratios as well as the use of `vw` and `vh`.
